### ISSUE TITLE
Add requirements.txt or pipfile

### ISSUE THREAD

**Issue by matthewfeickert** [36000/HFSF#1]
Hi @36000 and @balbok0 this is all great, but it would be nice if you could add either a `requirements.txt` or a `pipfile` with all the required dependencies so that someone can easily setup a virtual environment to reproduce your results.

**Comment by balbok0** [comment]
Hi, just pushed the requirements.md file which contains required packages, and pip line to install them.
Note that smac3 requires python >=3.5.2, which can be a little annoying (use pip3 instead of pip, if python 2.7 is default on your system).

**Comment by balbok0** [comment]
Let me know, if I missed some of the packages.
